- hosts: bookstore
  sudo: yes
  roles:
    - common

- hosts: shopping
  sudo: yes
  roles:
    - { role: bookstore, context: 'shopping' }

- hosts: order
  sudo: yes
  roles:
    - { role: bookstore, context: 'order' }

- hosts: product
  sudo: yes
  roles:
    - { role: bookstore, context: 'product' }
