- name: Copy jar files
  copy: src=../deploy-jars/{{ jar_file }} dest=/home/vagrant/{{ jar_file }} owner=vagrant group=vagrant mode=0644

- name: Copy configuration
  template: src="{{ yml_file }}.j2" dest=/home/vagrant/{{ yml_file }} owner=vagrant group=vagrant mode=0644
  notify:
    - restart bookstore

- name: Setup service init file
  template: src=init.d.j2 dest=/etc/init.d/{{ context }} owner=root group=root mode=0744

# Ensure service is running
- service: name={{ context }} state=started enabled=yes
